services:
  pihole:
    image: pihole/pihole:2024.07
    restart: always
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: {{ WEBPASSWORD }}
      PIHOLE_DNS_: {{ PIHOLE_DNS }}
      FTLCONF_LOCAL_IPV4: {{ FTLCONF_LOCAL_IPV4 }}
      DHCP_IPv6: true
      # WEB_PORT: 80
      DNSMASQ_LISTENING: all
      CORS_HOSTS: {{ CORS_HOSTS }}
    volumes:
      - type: volume
        source: pihole_data
        target: /etc/pihole
      - type: volume
        source: pihole_dnsmasq
        target: /etc/dnsmasq.d

volumes:
  pihole_data:
  pihole_dnsmasq: