services:
  app:
    image: nextcloud:28.0.7
    restart: on-failure
    volumes:
      - type: volume
        source: html_folder
        target: /var/www/html
      - type: volume
        source: backup
        target: /backup
    environment:
      POSTGRES_DB: {{ POSTGRES_DB }}
      POSTGRES_USER: {{ POSTGRES_USER }}
      POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
      POSTGRES_HOST: {{ POSTGRES_HOST }}

      TRUSTED_PROXIES: {{TRUSTED_PROXIES}}

      NEXTCLOUD_ADMIN_USER: {{ NEXTCLOUD_ADMIN_USER }}
      NEXTCLOUD_ADMIN_PASSWORD: {{ NEXTCLOUD_ADMIN_PASSWORD }}
      
    networks:
      - {{ db_backend }}

volumes:
  html_folder:
  backup:

networks:
  {{ db_backend }}:
    external: true
