services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: {{ POSTGRES_PASSWORD }}
      # open psql terminal: ALTER USER postgres WITH PASSWORD 'new_password';
    volumes:
      - type: volume
        source: pg_data
        target: /var/lib/postgresql/data
    networks:
      - {{ db_backend }}

volumes:
  pg_data:
    
networks:
  {{ db_backend }}:
    external: true